project:
  type: website

website:
  title: "Education Test Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: notebooks/index.qmd
        text: Demo Notebooks
    right: 
        - href: https://github.com/Avery-s-Organization/EducationGrantSite
          icon: github
          aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  echo: true    # Ensures code is displayed correctly



