project:
  type: website
  render:
    - "*.qmd"
    - "schedule/*.qmd"
    - "project_1/index.qmd"
    - "notebooks/*.qmd"
    - "notebooks/*.Rmd"
    - "notebooks/*.ipynb"
    - "!project_1/materials/"
  resources:
    - "project_1/materials/*.ipynb"
    - "project_1/materials/AZ_DATA.csv"
    - "project_1/fictious_data.csv"

website:
  title: "Arizona Data Science Corps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule/schedule_2026_advanced.qmd
        text: Daily Schedule
      - href: faculty_applications.qmd
        text: DS Applications
      - href: about.qmd
        text: About
    right: 
        - href: https://github.com/AZDSC-NAU/AZDSC_NAU_SITE
          icon: github
          aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  echo: true    # Ensures code is displayed correctly
