project:
  type: website

website:
  title: "Arizona Data Science Corps"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project_1/index.qmd
        text: Advanced Projects
      - href: faculty_applications.qmd
        text: DS Applications
      - href: about.qmd
        text: About
    right: 
        - href: https://github.com/AZDSC-NAU/AZDSC_NAU_SITE
          icon: github
          aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  echo: true    # Ensures code is displayed correctly



